language: ruby
rvm:
  - 1.9.3

env:
  - SUITE="rake spec"
  - SUITE="cucumber -ptravis"

notifications:
  recipients:
    - main@sharetribe.flowdock.com
    - main@kassi.flowdock.com
    - suomi@kassi.flowdock.com

branches:
  only:
    - master
    - develop

before_script:
  - cp config/database.example.yml config/database.yml
  - mysql -e 'create database sharetribe_test;'
  - rake db:test:load

script:
  - PHANTOMJS=true NO_WEBDRIVER_MONKEY_PATCH=true bundle exec $SUITE

