default: &default_settings
  
  #This is the url of the ASI server you want to use
  asi_url: "http://cos.alpha.sizl.org"
  # The following url will be used when handling passwords
  # So if the ASI server supports https, you can specify a https uls
  # This can be same as asi_url if no https is available
  ssl_asi_url: "https://cos.alpha.sizl.org"

  # These are the credentials used to log on to ASI server. 
  # The defaults will work for
  # OtaSizzle's test server, an can be used for testing Kassi.
  asi_app_name: kassi_testing
  asi_app_password: kassi_tester

  # The default locale (language) of the user interface
  default_locale: en
  
  # reCAPTChA is used to avoid bots registering accounts
  # You need to register your domain at https://www.google.com/recaptcha
  # to get the keys
  use_recaptcha: false
  recaptcha_public_key: 'enter_your_own_key_here'
  recaptcha_private_key: 'enter_your_own_key_here'  

  # Ressi is Researcher's Interface for logged data
  # If you don't need it just leave it to false
  # If log_to_ressi is false, other ressi settings can be ignored.
  log_to_ressi: false
  ressi_url: "http://cos.alpha.sizl.org/ressi"
  ressi_timeout: 5
  ressi_upload_hour: 1

  # This will be the from field in the mails sent from Kassi
  kassi_mail_from_address: "noreply-kassi@example.com"
  
  # The address where the notifications of feedbacks from Kassi UI are sent
  feedback_mailer_recipients:  'admins@example.com'

  # If you want to get mail notification of errors that happen in Kassi
  # you can specify it here. Otherwise leave to be false.
  use_error_mailer: false
  error_mailer_recipients: 'admins@example.com'
  error_mailer_from_address: 'Error Mailer <KassiErrors@example.com>'

  # New relic is a software used for performance testing
  # Leave to false unless you need it
  use_newrelic: false

  # CAS is a centralized authentication system, it is completely optional
  # If not needed leave to false
  use_CAS: false

  
  
  # Below it is possible to specify different settings for different
  # environments. If you are not developing or testing Kassi, you 
  # don't need to change those
  # ----------------------------------------------------------------


production:
  <<: *default_settings


development:
  <<: *default_settings
  
test:
  <<: *default_settings
  # The locale should be "en" for test environment
  # even if you change it for others
  default_locale: en
  

